apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.data }}
    {{$key}}: {{ $val | b64enc | quote }}
    {{- end }}
