{
 "title": "MIDL.dev status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "MIDL.dev Tezos Node clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MIDL.dev Toronto",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT status, \"time\" from cluster_status WHERE cluster = 'MIDL.dev Toronto' AND $__timeFilter(time) ORDER BY \"time\" DESC LIMIT 200; "
    }
   ]
  },
  {
   "title": "MIDL.dev Amsterdam",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT status, \"time\" from cluster_status WHERE cluster = 'MIDL.dev Amsterdam' AND $__timeFilter(time) ORDER BY \"time\" DESC LIMIT 200; "
    }
   ]
  },
  {
   "title": "MIDL.dev served Tezos RPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "MIDL.dev Toronto cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rpc requests/min" } },
   "targets": [
    {
     "rawSql": "SELECT count AS \"number of rpc requests\", \"time\" FROM request_counts WHERE cluster = 'MIDL.dev Toronto' AND $__timeFilter(\"time\") LIMIT 2000;"
    }
   ]
  },
  {
   "title": "MIDL.dev Amsterdam cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "rpc requests/min" } },
   "targets": [
    {
     "rawSql": "SELECT count AS \"number of rpc requests\", \"time\" FROM request_counts WHERE cluster = 'MIDL.dev Amsterdam' AND $__timeFilter(\"time\") LIMIT 2000;"
    }
   ]
  }
 ]
}