"""empty message

Revision ID: 888c03d17df7
Revises: b8bc19bdb95a
Create Date: 2023-08-23 13:09:29.448147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888c03d17df7'
down_revision = 'b8bc19bdb95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_counts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), server_default="general", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_counts', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
