apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-status-server
  labels:
    {{- include "midl-status.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: status-server
spec:
  replicas: {{ .Values.statusServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "midl-status.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: status-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "midl-status.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: status-server
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/flask-core/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.statusServer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.statusServer.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.statusServer.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.statusServer.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-config
            - secretRef:
                name: {{.Release.Name}}-secret
          ports:
            - name: flask
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.statusServer.resources | nindent 12 }}
      {{- with .Values.statusServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.statusServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.statusServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
